"""Initial migration: migrate in-memory to postgres

Revision ID: 5956209c91d3
Revises: 
Create Date: 2026-03-20 17:14:50.575145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5956209c91d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bounties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reward_amount', sa.BigInteger(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounties_issue_number'), 'bounties', ['issue_number'], unique=True)
    op.create_table('contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('wallet_address', sa.String(length=44), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('t1_completions', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributors_github_id'), 'contributors', ['github_id'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bounty_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('pr_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], ),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_index(op.f('ix_contributors_github_id'), table_name='contributors')
    op.drop_table('contributors')
    op.drop_index(op.f('ix_bounties_issue_number'), table_name='bounties')
    op.drop_table('bounties')
    # ### end Alembic commands ###
