"""complete_auth_schema

Revision ID: d2394f768088
Revises: 5956209c91d3
Create Date: 2026-03-21 00:00:11.596233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2394f768088'
down_revision: Union[str, Sequence[str], None] = '5956209c91d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributors', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('contributors', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('contributors', 'github_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('contributors', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('contributors', 'wallet_address',
               existing_type=sa.VARCHAR(length=44),
               nullable=True)
    op.create_index(op.f('ix_contributors_wallet_address'), 'contributors', ['wallet_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributors_wallet_address'), table_name='contributors')
    op.alter_column('contributors', 'wallet_address',
               existing_type=sa.VARCHAR(length=44),
               nullable=False)
    op.alter_column('contributors', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contributors', 'github_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('contributors', 'created_at')
    op.drop_column('contributors', 'avatar_url')
    # ### end Alembic commands ###
