"""Add contributor and reputation models

Revision ID: f0c2b6f0152a
Revises: 
Create Date: 2026-03-21 16:41:09.446431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c2b6f0152a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('badges', sa.JSON(), nullable=False),
    sa.Column('social_links', sa.JSON(), nullable=False),
    sa.Column('total_contributions', sa.Integer(), nullable=False),
    sa.Column('total_bounties_completed', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.Float(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributors_username'), 'contributors', ['username'], unique=True)
    op.create_table('reputation_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('bounty_title', sa.String(length=255), nullable=False),
    sa.Column('bounty_tier', sa.Integer(), nullable=False),
    sa.Column('review_score', sa.Float(), nullable=False),
    sa.Column('earned_reputation', sa.Float(), nullable=False),
    sa.Column('anti_farming_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_history_bounty_id'), 'reputation_history', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_reputation_history_contributor_id'), 'reputation_history', ['contributor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reputation_history_contributor_id'), table_name='reputation_history')
    op.drop_index(op.f('ix_reputation_history_bounty_id'), table_name='reputation_history')
    op.drop_table('reputation_history')
    op.drop_index(op.f('ix_contributors_username'), table_name='contributors')
    op.drop_table('contributors')
    # ### end Alembic commands ###
