import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Sparkles, Copy, CheckCircle, Loader2, AlertCircle, RefreshCw } from 'lucide-react';
import { PageLayout } from '../components/layout/PageLayout';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface Enhancement {
  style: string;
  model: string;
  enhanced_title: string;
  enhanced_description: string;
  acceptance_criteria: string[];
  examples: string[];
}

interface ApiResponse {
  success: boolean;
  originals: { title: string; description: string };
  enhancements: Enhancement[];
  message: string;
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  const handleCopy = async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button
      onClick={handleCopy}
      className="flex items-center gap-1 text-xs text-text-secondary hover:text-emerald transition-colors"
    >
      {copied ? <CheckCircle size={14} className="text-emerald" /> : <Copy size={14} />}
      {copied ? 'Copied!' : 'Copy'}
    </button>
  );
}

function EnhancementCard({ enhancement, idx }: { enhancement: Enhancement; idx: number }) {
  const markdown = `## ${enhancement.enhanced_title}

${enhancement.enhanced_description}

### Acceptance Criteria
${enhancement.acceptance_criteria.map((ac) => `- ${ac}`).join('\n')}

### Examples
${enhancement.examples.map((ex) => `- ${ex}`).join('\n')}`;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: idx * 0.15 }}
      className="bg-forge-900/60 border border-border/50 rounded-xl p-5 backdrop-blur-sm"
    >
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-full bg-emerald/10 flex items-center justify-center">
            <Sparkles size={14} className="text-emerald" />
          </div>
          <span className="text-sm font-medium text-text-primary">{enhancement.style}</span>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs text-text-secondary/60">{enhancement.model}</span>
          <CopyButton text={markdown} />
        </div>
      </div>

      <div className="prose prose-invert prose-sm max-w-none">
        <h3 className="text-base font-semibold text-emerald mb-2">{enhancement.enhanced_title}</h3>
        <p className="text-text-secondary text-sm leading-relaxed">{enhancement.enhanced_description}</p>

        {enhancement.acceptance_criteria.length > 0 && (
          <>
            <h4 className="text-xs font-medium text-text-secondary/70 uppercase tracking-wider mt-4 mb-2">Acceptance Criteria</h4>
            <ul className="space-y-1">
              {enhancement.acceptance_criteria.map((ac, i) => (
                <li key={i} className="text-text-secondary text-sm flex items-start gap-2">
                  <span className="text-emerald/70 mt-1">•</span>
                  {ac}
                </li>
              ))}
            </ul>
          </>
        )}

        {enhancement.examples.length > 0 && (
          <>
            <h4 className="text-xs font-medium text-text-secondary/70 uppercase tracking-wider mt-4 mb-2">Examples</h4>
            <ul className="space-y-1">
              {enhancement.examples.map((ex, i) => (
                <li key={i} className="text-text-secondary text-sm">{ex}</li>
              ))}
            </ul>
          </>
        )}
      </div>
    </motion.div>
  );
}

function generateGitHubMarkdown(enhancements: Enhancement[]): string {
  let md = `<!-- Auto-generated by SolFoundry AI Enhancer -->\n\n`;
  enhancements.forEach((e, i) => {
    md += `## Option ${i + 1}: ${e.style}\n\n`;
    md += `### ${e.enhanced_title}\n\n`;
    md += `${e.enhanced_description}\n\n`;
    if (e.acceptance_criteria.length > 0) {
      md += `#### Acceptance Criteria\n`;
      e.acceptance_criteria.forEach((ac) => (md += `- ${ac}\n`));
      md += '\n';
    }
    if (e.examples.length > 0) {
      md += `#### Examples\n`;
      e.examples.forEach((ex) => (md += `- ${ex}\n`));
      md += '\n';
    }
    md += `---\n\n`;
  });
  return md;
}

const BENEFITS = [
  { label: 'More clarity', desc: 'Clear requirements → better submissions' },
  { label: 'Higher quality', desc: 'Detailed ACs attract serious contributors' },
  { label: 'Faster reviews', desc: 'Well-defined bounties are easier to evaluate' },
];

export function EnhancePage() {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ApiResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copiedAll, setCopiedAll] = useState(false);

  const handleEnhance = async () => {
    if (!title.trim() || !description.trim()) return;

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const resp = await fetch('/api/enhance-bounty', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title: title.trim(), description: description.trim() }),
      });
      if (!resp.ok) throw new Error(`HTTP ${resp.status}: ${await resp.text()}`);
      const data: ApiResponse = await resp.json();
      setResult(data);
    } catch (err: any) {
      setError(err.message || 'Failed to enhance. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const copyAllToClipboard = async () => {
    if (!result) return;
    const md = generateGitHubMarkdown(result.enhancements);
    await navigator.clipboard.writeText(md);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 3000);
  };

  return (
    <PageLayout>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="max-w-6xl mx-auto px-4 py-12"
      >
        {/* Header */}
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-emerald/5 border border-emerald/20 rounded-full text-emerald text-xs font-medium mb-4">
            <Sparkles size={12} />
            AI-Powered
          </div>
          <h1 className="font-display text-4xl font-bold text-text-primary mb-3">
            Bounty Description Enhancer
          </h1>
          <p className="text-text-secondary text-lg max-w-2xl mx-auto">
            Paste a rough idea — get 3 polished versions with acceptance criteria, examples, and GitHub-ready markdown.
          </p>
        </div>

        {/* Benefits */}
        <div className="flex flex-wrap justify-center gap-4 mb-10">
          {BENEFITS.map((b) => (
            <div key={b.label} className="bg-forge-900/40 border border-border/30 rounded-lg px-4 py-3 text-center">
              <div className="text-sm font-medium text-text-primary">{b.label}</div>
              <div className="text-xs text-text-secondary/70 mt-0.5">{b.desc}</div>
            </div>
          ))}
        </div>

        {/* Input Form */}
        <div className="bg-forge-900/60 border border-border/50 rounded-xl p-6 mb-8 backdrop-blur-sm">
          <div className="mb-4">
            <label className="block text-sm font-medium text-text-secondary mb-2">Bounty Title</label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g., Add dark mode support"
              className="w-full bg-forge-950/80 border border-border/50 rounded-lg px-4 py-2.5 text-text-primary placeholder-text-secondary/40 focus:outline-none focus:border-emerald/50 transition-colors"
              maxLength={200}
            />
          </div>

          <div className="mb-4">
            <label className="block text-sm font-medium text-text-secondary mb-2">Bounty Description</label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Describe the bounty — what needs to be built, why it matters, any constraints..."
              rows={5}
              className="w-full bg-forge-950/80 border border-border/50 rounded-lg px-4 py-2.5 text-text-primary placeholder-text-secondary/40 focus:outline-none focus:border-emerald/50 transition-colors resize-vertical"
              maxLength={5000}
            />
          </div>

          <div className="flex items-center justify-between">
            <span className="text-xs text-text-secondary/60">
              {description.length}/5000 characters
            </span>
            <button
              onClick={handleEnhance}
              disabled={loading || !title.trim() || !description.trim()}
              className="flex items-center gap-2 px-5 py-2.5 bg-emerald hover:bg-emerald/90 disabled:bg-emerald/30 disabled:cursor-not-allowed text-forge-950 font-medium rounded-lg transition-all active:scale-95"
            >
              {loading ? (
                <>
                  <Loader2 size={16} className="animate-spin" />
                  Enhancing...
                </>
              ) : (
                <>
                  <Sparkles size={16} />
                  Enhance
                </>
              )}
            </button>
          </div>
        </div>

        {/* Error */}
        {error && (
          <div className="flex items-center gap-2 bg-red-500/10 border border-red-500/20 rounded-lg px-4 py-3 mb-6">
            <AlertCircle size={16} className="text-red-400 shrink-0" />
            <span className="text-red-300 text-sm">{error}</span>
          </div>
        )}

        {/* Results */}
        {result && (
          <div>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-text-primary">
                Enhanced Versions
                <span className="text-text-secondary/60 text-sm ml-2 font-normal">{result.message}</span>
              </h2>
              <button
                onClick={copyAllToClipboard}
                className="flex items-center gap-2 px-3 py-1.5 bg-forge-800/80 border border-border/50 rounded-lg text-xs text-text-secondary hover:text-emerald transition-colors"
              >
                {copiedAll ? <CheckCircle size={14} className="text-emerald" /> : <Copy size={14} />}
                {copiedAll ? 'Copied all to clipboard!' : 'Copy all as markdown'}
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
              {result.enhancements.map((e, i) => (
                <EnhancementCard key={i} enhancement={e} idx={i} />
              ))}
            </div>

            {/* Original */}
            <details className="group">
              <summary className="text-sm text-text-secondary/50 hover:text-text-secondary/70 cursor-pointer transition-colors">
                Show original input
              </summary>
              <div className="mt-2 p-3 bg-forge-950/40 border border-border/20 rounded-lg">
                <p className="text-xs text-text-secondary/50 mb-1">Original title:</p>
                <p className="text-sm text-text-secondary mb-3">{result.originals.title}</p>
                <p className="text-xs text-text-secondary/50 mb-1">Original description:</p>
                <p className="text-sm text-text-secondary">{result.originals.description}</p>
              </div>
            </details>
          </div>
        )}

        {/* Initial state hint */}
        {!result && !loading && !error && (
          <div className="text-center py-8">
            <RefreshCw size={32} className="mx-auto text-text-secondary/20 mb-3" />
            <p className="text-text-secondary/40 text-sm">
              Paste a bounty idea above and click Enhance to get started
            </p>
          </div>
        )}
      </motion.div>
    </PageLayout>
  );
}
