import { useState } from 'react';
import { apiClient } from '../services/apiClient';

interface LLMEnhancement {
  llm_name: string;
  enhanced_title: string;
  enhanced_description: string;
  acceptance_criteria: string[];
  examples: string[];
}

interface EnhanceResponse {
  enhancements: LLMEnhancement[];
  aggregated: LLMEnhancement;
}

export default function EnhancePage() {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState<EnhanceResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleEnhance = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await apiClient<EnhanceResponse>('/api/enhance-bounty', {
        method: 'POST',
        body: { title, description },
      });
      setResponse(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to enhance');
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
  };

  const generateMarkdown = (e: LLMEnhancement) => {
    return `# ${e.enhanced_title}\n\n## Description\n${e.enhanced_description}\n\n## Acceptance Criteria\n${e.acceptance_criteria.map((c) => `- [ ] ${c}`).join('\n')}\n\n## Examples\n${e.examples.map((x) => `- ${x}`).join('\n')}\n\n*Generated by ${e.llm_name}*`;
  };

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-6xl mx-auto px-4">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">AI Bounty Description Enhancer</h1>
        <p className="text-gray-600 mb-8">Transform vague bounty ideas into clear, actionable issues using multiple LLMs</p>

        <div className="bg-white rounded-lg shadow p-6 mb-8">
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Bounty Title (vague)</label>
              <input type="text" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g., Add notifications" className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Description (rough idea)</label>
              <textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="e.g., Users should get notified when something happens" rows={4} className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />
            </div>
            <button onClick={handleEnhance} disabled={loading} className="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 disabled:opacity-50">
              {loading ? 'Enhancing with 3 LLMs...' : 'Enhance Bounty Description'}
            </button>
            {error && <p className="text-red-600 text-sm mt-2">{error}</p>}
          </div>
        </div>

        {response && (
          <div className="space-y-8">
            <div className="bg-green-50 border border-green-200 rounded-lg p-6">
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-xl font-bold text-gray-900">🎯 Aggregated Result (Recommended)</h2>
                <button onClick={() => copyToClipboard(generateMarkdown(response.aggregated))} className="bg-green-600 text-white text-sm py-1 px-3 rounded hover:bg-green-700">📋 Copy Markdown</button>
              </div>
              <div className="prose max-w-none">
                <h3 className="text-lg font-semibold">{response.aggregated.enhanced_title}</h3>
                <p className="text-gray-700">{response.aggregated.enhanced_description}</p>
                <h4 className="font-medium mt-4">Acceptance Criteria:</h4>
                <ul className="list-disc list-inside space-y-1">{response.aggregated.acceptance_criteria.map((c, i) => <li key={i} className="text-gray-700">{c}</li>)}</ul>
                <h4 className="font-medium mt-4">Examples:</h4>
                <ul className="list-disc list-inside space-y-1">{response.aggregated.examples.map((e, i) => <li key={i} className="text-gray-700">{e}</li>)}</ul>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {response.enhancements.map((e, idx) => (
                <div key={idx} className="bg-white rounded-lg shadow p-6">
                  <div className="flex justify-between items-center mb-4">
                    <h3 className="font-bold text-gray-900">{e.llm_name}</h3>
                    <button onClick={() => copyToClipboard(generateMarkdown(e))} className="text-sm text-blue-600 hover:underline">Copy</button>
                  </div>
                  <div className="space-y-4">
                    <div><p className="text-sm font-medium text-gray-700 mb-1">Title:</p><p className="text-sm text-gray-900">{e.enhanced_title}</p></div>
                    <div><p className="text-sm font-medium text-gray-700 mb-1">Description:</p><p className="text-sm text-gray-700">{e.enhanced_description}</p></div>
                    <div><p className="text-sm font-medium text-gray-700 mb-1">Criteria:</p><ul className="text-sm text-gray-700 list-disc list-inside space-y-1">{e.acceptance_criteria.map((c, i) => <li key={i}>{c}</li>)}</ul></div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
